version: '3'

services:
  express-docker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/express-docker
    

  frontend:
    build:
      context: ./vermieteMeinZuhause
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
